
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.Common;

namespace DAY5EXercise
{
	public class Employees : _Employees
	{		
		public Employees() 
		{
			this.DefaultCommandType = CommandType.StoredProcedure;
		}

		// Place your custom code here.
	}
}
